version: 2.0

jobs:
    build:
        docker:
            - image: gradle:alpine
        environment:
          MAVEN_CLI_OPTS: "--batch-mode"
        steps:
            - checkout
            - run: gradle build
            - store_artifacts:
                path: target
                destination: target
                
    test:
        docker:
            - image: sugan1234/vaadin:v1
        steps:
            - checkout
            - run: gradle test
            - store_artifacts:
                path: reports
                destination: reports

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
        requires:
          - build